# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f7ec1191c66e6e6ed3c703d0345aaeb55d62e25954e07157df00a271a02334750d029ac3fca906094ebdadd4219e5dc818703c91e7a249d27712861f224142a

test:
  secret_key_base: fd72b43a8d9942fbacb306eec1212c53a1306e717915735b8cc0d399ed592c487a67109851c44b6d33bc681991d3b095ac3c4d657eaed05caccd18fbae2b8a5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
